# Generated by Django 3.0 on 2019-12-30 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_netdisk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
