# Generated by Django 3.0 on 2019-12-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('django_netdisk', '0002_file_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
