# Generated by Django 3.0 on 2019-12-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_netdisk', '0003_file_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='group',
            new_name='groups',
        ),
    ]
