# Generated by Django 3.0 on 2020-01-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excelwork', '0002_excel_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excels', to=settings.AUTH_USER_MODEL),
        ),
    ]
