# Generated by Django 3.0 on 2020-01-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelwork', '0003_auto_20200112_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='客户',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('姓名', models.CharField(max_length=31)),
                ('下单时间', models.DateTimeField()),
                ('联系方式', models.CharField(max_length=31)),
                ('购货时间', models.DateTimeField()),
                ('excel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelwork.Excel')),
            ],
        ),
    ]
